### ISSUE TITLE
Fatal error: This socket is closed.

### ISSUE THREAD

**Issue by Chris2011** [sapegin/grunt-webfont#149]
I use Windows 7 64bit, I installed grunt-webfont via npm install and after this I only have:

``` bash
webfont: {
   icons: {
      src: "icons/*.svg",
      dest: "public/project/font"
   }
}
```

and when I run grunt webfont, I got this error:

``` bash
Running "webfont:icons" (webfont) task
Fatal error: This socket is closed.
```

At the installation, there was no problem.

Regards

Chris

**Comment by thybzi** [comment]
Getting the similar problem on Windows with `node` engine:
```
Running "webfont:icons" (webfont) task
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed.
    at WriteStream.Socket._writeGeneric (net.js:640:19)
    at WriteStream.Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at WriteStream.Writable.write (_stream_writable.js:207:11)
    at WriteStream.Socket.write (net.js:618:40)
    at Log._write (D:\repo\titr\node_modules\grunt\node_modules\grunt-legacy-log\index.js:161:26)
    at Log.bound [as _write] (D:\repo\titr\node_modules\grunt\node_modules\grunt-legacy-log\node_modules\lodash\d
    at Log._writeln (D:\repo\titr\node_modules\grunt\node_modules\grunt-legacy-log\index.js:166:8)
    at Log.bound [as _writeln] (D:\repo\titr\node_modules\grunt\node_modules\grunt-legacy-log\node_modules\lodash
```

**Comment by thybzi** [comment]
UPD. Seems that it was autohint issue (I have no `ttfautohint` installed, just trying for now).
Didn't mention `autoHint` option is `true` by default. 
Changing to `autoHint: false` solved my problem.
Sorry for the trouble.

**Comment by sapegin** [comment]
Of course it’s [mentioned in the docs](https://github.com/sapegin/grunt-webfont#autohint).
