### ISSUE TITLE
Error trying to upgrade to the latest version

### ISSUE THREAD

**Issue by juarezpaf** [sapegin/grunt-webfont#236]
I'm using `0.4.8` version, when I tried to update to the latest version just got this error:
```
Running "webfont:dist" (webfont) task
Fatal error: Unexpected character "N" at index 1.
```

**Comment by sapegin** [comment]
Could you please share your Gruntfile?

**Comment by juarezpaf** [comment]
Hi @sapegin, we split each task into a JS module, below you can see the `.grunt/assets/webfont.js`
Thanks in advance!

```
var path = require('path');

module.exports = {
	dist: {
		options: {
			hashes: false,
			engine: 'node',
			stylesheet: 'scss',
			htmlDemo: true,
			relativeFontPath: '../fonts',
			template: '.grunt/_templates/webfont-template.css',
			htmlDemoTemplate: '.grunt/_templates/webfont-template.html',
			templateOptions: {
				classPrefix: 'icon-',
			},
			rename: function (name) {
				name = name.replace('-grey', '');
				name = name.toLowerCase();

				return [path.basename(path.dirname(name)), path.basename(name)].join('-');
			}
		},

		src: '<%= paths.original.svg %>/**/*.svg',
		dest: '<%= paths.original.fonts %>',
		destCss: '<%= paths.original.sass %>/font',
	}
};

```

**Comment by sapegin** [comment]
Could you also post your templates (webfont-template.css and webfont-template.html) and result of `grunt webfont --stack`?

**Comment by juarezpaf** [comment]
Hi @sapegin sorry for this delayed message, here you go:

`grunt webfont --stack`
```
[(ruby-2.1.2)] ~/Dropbox/playground/withlove/farmony <develop> ✗ grunt webfont --stack
Running "webfont:dist" (webfont) task
Fatal error: Unexpected character "N" at index 1.
SyntaxError: Unexpected character "N" at index 1.
    at SVGPathDataParser._transform (/Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/node_modules/svg-pathdata/src/SVGPathDataParser.js:455:28)
    at SVGPathDataParser.Transform._read (/Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at SVGPathDataParser.Transform._write (/Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at SVGPathDataParser.Writable.write (/Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Function.SVGPathData.parse (/Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/node_modules/svg-pathdata/src/SVGPathData.js:112:10)
    at new SVGPathData (/Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/node_modules/svg-pathdata/src/SVGPathData.js:2:31)
    at /Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/src/index.js:224:20
    at Array.forEach (native)
    at /Users/gabstrweb/Dropbox/playground/withlove/farmony/node_modules/grunt-webfont/node_modules/svgicons2svgfont/src/index.js:223:19
    at Array.forEach (native)
```

And `webfont-template.css`
```
// Webfont
//
//////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////

<% if (fontfaceStyles) { %>
<% if (fontSrc1) { %>
@font-face {
	font-family:"<%= fontBaseName %>";
	src:<%= fontSrc1 %>;
	font-weight:normal;
	font-style:normal;
}
<% } %>
@font-face {
	font-family:"<%= fontBaseName %>";<% if (fontSrc1) { %>
	src:<%= fontSrc1 %>;<% }%>
	src:<%= fontSrc2 %>;
	font-weight:normal;
	font-style:normal;
}
<% } %>

%icon {
	 display: inline-block;
	 vertical-align: middle;

	 text-transform: none;
	 text-decoration: inherit;
	 text-rendering: optimizeLegibility;

	 line-height: 1;

	 font-family:"<%= fontBaseName %>";
	 font-weight: normal;
	 font-smoothing: antialiased;
	 font-style: normal;
	 speak: none;
 }

.<%= baseClass %> {
	@extend %icon;
}

<% if (iconsStyles) { %>/* Icons */<% for (var glyphIdx = 0; glyphIdx < glyphs.length; glyphIdx++) { %>
.<%= classPrefix %><%= glyphs[glyphIdx] %>:before {
  content:"<% if (addLigatures) { %><%= glyphs[glyphIdx] %><% } else { %>\<%= codepoints[glyphIdx] %><% } %>";
}<% } %>
<% } %>
```

Finally `webfont-template.html`
```
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title><%= fontBaseName %></title>
	<style>
		body {
			margin:0;
			padding:10px 20px;
			background:#fff;
			color:#222;
		}
		h1, div, footer {
			font-family:"Helvetica Neue", Arial, sans-serif;
		}
		h1 {
			margin:0 0 20px;
			font-size:32px;
			font-weight:normal;
		}
		.icons {
			margin-bottom:40px;
			-webkit-column-count:5;
			-moz-column-count:5;
			column-count:5;
			-webkit-column-gap:20px;
			-moz-column-gap:20px;
			column-gap:20px;
		}
		.icons__item,
		.icons__item i {
			line-height:2em;
			cursor:pointer;
		}
		.icons__item:hover {
			color:#3c90be;
		}
		.icons__item i {
			display:inline-block;
			width:32px;
			text-align:center;
		}
		.icons__item:hover i {
			-webkit-transform:scale(1.5);
			transform:scale(1.5);
		}
		footer {
			margin-top:40px;
			font-size:14px;
			color:#999;
		}
	</style>
	<link rel="stylesheet" href="../../css/styles.css" />
</head>
<body>
	<h1><%= fontBaseName %></h1>

	<div class="icons" id="icons">
		<% for (var glyphIdx = 0; glyphIdx < glyphs.length; glyphIdx++) { var glyph = glyphs[glyphIdx] %>
		<div class="icons__item" data-name="<%= glyph %>"><i class="<%= baseClass %> <%= classPrefix %><%= glyph %>"></i> <%= classPrefix %><%= glyph %></div>
		<% } %>
	</div>

	<% if (addLigatures) { %>
	<div class="ligature-icons" style="display:none">
		<% for (var glyphIdx = 0; glyphIdx < glyphs.length; glyphIdx++) { var glyph = glyphs[glyphIdx]; %>
		<%= glyph %>
		<% } %>
	</div>
	<% } %>

	<h1>Usage</h1>
	<pre><code>&lt;i class=&quot;<%= baseClass ? baseClass + ' ' : '' %><%= classPrefix %><span id="name">name</span>&quot;&gt;&lt;/i&gt;</code></pre>
	<% if (addLigatures) { %>
	<pre><code>&lt;i class=&quot;ligature-icons&quot;&gt;<span id="name2">name</span>&lt;/i&gt;</code></pre>
	<% } %>

	<footer>Generated by <a href="https://github.com/sapegin/grunt-webfont">grunt-webfont</a>.</footer>

	<script>
		(function() {
			document.getElementById('icons').onclick = function(e) {
				e = e || window.event;
				var name = e.target.getAttribute('data-name') || e.target.parentNode.getAttribute('data-name');
				document.getElementById('name').innerHTML = name;
				document.getElementById('name2').innerHTML = name;
			}
		})();
	</script>
</body>
</html>
```

Thanks in advance!

**Comment by nfroidure** [comment]
Hi!

Looks like there is a NaN in some SVG Path.

Could you please provide the icon leading to this problem by discrimate him progressively?

Thanks.

**Comment by sapegin** [comment]
Feel free to reopen if you still have this issue.
