### ISSUE TITLE
Error: Failed to download resource "libpng"

### ISSUE THREAD

**Issue by monolithed** [sapegin/grunt-webfont#260]
```js
webfont: {
	icons: {
		src    : 'ico.svg',
		dest   : 'ico.base64',
		options: {
			types: ['eot']
		}
	}
}
```
It's really easy to convert using other npm modules.
I don't understand why i should install something else.

`brew`, `ttfautohint`, `fontforge`, `libpng`

Are you kidding?

```
➜ brew install ttfautohint fontforge --with-python
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libpng"
Download failed: https://downloads.sf.net/project/libpng/libpng16/1.6.13/libpng-1.6.13.tar.xz
```

**Comment by monolithed** [comment]
Solution:

```
cd $(brew --prefix)
git clean -fd
git reset --hard HEAD
brew update
```

**Comment by monolithed** [comment]
```
➜ brew install ttfautohint fontforge --with-python
Warning: ttfautohint-1.3 already installed
==> Installing dependencies for fontforge: pango, zeromq, czmq, jpeg, libtiff
==> Installing fontforge dependency: pango
==> Downloading https://download.gnome.org/sources/pango/1.36/pango-1.36.8.tar.xz
Already downloaded: /Library/Caches/Homebrew/pango-1.36.8.tar.xz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/pango/1.36.8_1 --enable-man --with-html-dir=/usr/local/Cellar/
==> make
==> make install
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:483:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/formula_installer.rb:360:in `install_dependency'
/usr/local/Library/Homebrew/formula_installer.rb:318:in `block in install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:318:in `each'
/usr/local/Library/Homebrew/formula_installer.rb:318:in `install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:222:in `compute_and_install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:149:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:166:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:124:in `<main>'
```

Ha

**Comment by monolithed** [comment]
Вы сделали все чтобы я навсегда забыл что это за пакет.

**Comment by sapegin** [comment]
Of course you shouldn’t.
