### ISSUE TITLE
TypeError: sfntData.buffer.slice is not a function

### ISSUE THREAD

**Issue by MoOx** [sapegin/grunt-webfont#266]
I am working back on an old project and when I freshly installed all node_modules to run test I got a weird error (the simple task is building one icon only **taken from your tests**)

```
TypeError: sfntData.buffer.slice is not a function
  at ttf2woff (/.../happyplan/node_modules/grunt-webfont/node_modules/ttf2woff/index.js:198:39)
  at /.../happyplan/node_modules/grunt-webfont/tasks/engines/node.js:68:16
  at getFont (/.../happyplan/node_modules/grunt-webfont/tasks/engines/node.js:99:4)
  at Object.generators.woff (/.../happyplan/node_modules/grunt-webfont/tasks/engines/node.js:67:4)
  at getFont (/.../happyplan/node_modules/grunt-webfont/tasks/engines/node.js:102:20)
  at /.../happyplan/node_modules/grunt-webfont/tasks/engines/node.js:108:4
  at fn (/.../happyplan/node_modules/grunt-webfont/node_modules/async/lib/async.js:582:34)
  at Immediate._onImmediate (/.../happyplan/node_modules/grunt-webfont/node_modules/async/lib/async.js:498:34)
  at processImmediate [as _immediateCallback] (timers.js:371:17)
```

Any idea?

**Comment by nfroidure** [comment]
Probably a semver issue. ttf2woff had a compatibility issue if i remember well. Add an older version of it to your peer deps or upgrade grunt-webfont.

**Comment by MoOx** [comment]
Upgrading to 0.5.4 fixed the issue indeed. Thanks.
