### ISSUE TITLE
FontForge process unexpectedly closes on build, stderr maxBuffer exceeded

### ISSUE THREAD

**Issue by TheEssemCraft** [sapegin/grunt-webfont#374]
OS: Ubuntu 14.04.5 LTS 
`fontforge` version: 20120731.b-5ubuntu0.1 
`grunt` version: 1.0.1 
`grunt-webfont` version: 1.6.0 

Here's the log:

```
$ npm run grunt webfont --verbose
npm info it worked if it ends with ok
npm verb cli [ '/home/travis/.nvm/versions/node/v9.2.0/bin/node',
npm verb cli   '/home/travis/.nvm/versions/node/v9.2.0/bin/npm',
npm verb cli   'run',
npm verb cli   'grunt',
npm verb cli   'webfont',
npm verb cli   '--verbose' ]
npm info using npm@5.5.1
npm info using node@v9.2.0
npm verb run-script [ 'pregrunt', 'grunt', 'postgrunt' ]
npm info lifecycle emojione-colr@0.2.2~pregrunt: emojione-colr@0.2.2
npm info lifecycle emojione-colr@0.2.2~grunt: emojione-colr@0.2.2

> emojione-colr@0.2.2 grunt /home/travis/build/TheEssemCraft/twemoji-colr
> grunt "webfont"

Running "webfont:Twemoji" (webfont) task
fontforge process has unexpectedly closed.
1. Try to run grunt in verbose mode to see fontforge output: grunt --verbose webfont.
2. If stderr maxBuffer exceeded try to increase execMaxBuffer, see https://github.com/sapegin/grunt-webfont#execMaxBuffer. 
Warning: stderr maxBuffer exceeded Use --force to continue.

Aborted due to warnings.
npm verb lifecycle emojione-colr@0.2.2~grunt: unsafe-perm in lifecycle true
npm verb lifecycle emojione-colr@0.2.2~grunt: PATH: /home/travis/.nvm/versions/node/v9.2.0/lib/node_modules/npm/bin/node-gyp-bin:/home/travis/build/TheEssemCraft/twemoji-colr/node_modules/.bin:./node_modules/.bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v9.2.0/bin:/home/travis/.kiex/elixirs/elixir-1.4.5/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/usr/local/phantomjs/bin:/usr/local/phantomjs:/usr/local/neo4j-3.2.1/bin:/usr/local/clang-3.9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin
npm verb lifecycle emojione-colr@0.2.2~grunt: CWD: /home/travis/build/TheEssemCraft/twemoji-colr
npm info lifecycle emojione-colr@0.2.2~grunt: Failed to exec grunt script
npm verb stack Error: emojione-colr@0.2.2 grunt: `grunt "webfont"`
npm verb stack Exit status 6
npm verb stack     at EventEmitter.<anonymous> (/home/travis/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
npm verb stack     at EventEmitter.emit (events.js:159:13)
npm verb stack     at ChildProcess.<anonymous> (/home/travis/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:159:13)
npm verb stack     at maybeClose (internal/child_process.js:943:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm verb pkgid emojione-colr@0.2.2
npm verb cwd /home/travis/build/TheEssemCraft/twemoji-colr
npm verb Linux 4.4.0-93-generic
npm verb argv "/home/travis/.nvm/versions/node/v9.2.0/bin/node" "/home/travis/.nvm/versions/node/v9.2.0/bin/npm" "run" "grunt" "webfont" "--verbose"
npm verb node v9.2.0
npm verb npm [0m v5.5.1
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! emojione-colr@0.2.2 grunt: `grunt "webfont"`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the emojione-colr@0.2.2 grunt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 6, true ]
```

**Comment by alampros** [comment]
See the [note in the readme on execMaxBuffer](https://github.com/sapegin/grunt-webfont#execmaxbuffer)

**Comment by TheEssemCraft** [comment]
@alampros I did what it said, still got the same result.
